### PR TITLE
chore(dependencies): Update dependencies.

### PR DESCRIPTION
**Pull request by acederberg**
Also updated ``--check`` flag to have an explicit ``off`` option.

### CODE REVIEW

**Review by shamrin — APPROVED** [review]
Looks good to me, thank you!

**Comment by shamrin** [comment]
@acederberg What's your use case for having `--no-check`? I would like to remove `--no-check`, because it makes `--help` and `README.md` easier to the eye. But I may be missing why `--no-check` is useful. Thanks!

**Comment by acederberg** [comment]
I just thought it would be nice to give it explicitly for scripts and what not in case the default value changes. Mostly, I did this out of habit and we would probably be fine without it tbh.

**Comment by shamrin** [comment]
@acederberg Thank you for information. I've removed `--no-check` and published made a new release. I've realized `--check` is not a 100% toggle. It mirrors the behavior of [`prettier --check`](https://prettier.io/docs/en/cli.html#--check).

https://github.com/shamrin/codeblocks/commit/773a83fe6fe59939427ea6c0a7102eab621fa11b

**Pull request merged**
